server:
  port: 12577
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
    url: jdbc:mysql://localhost:3306/articles_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false
#    hikari:
#      max-lifetime: 120000
#      auto-commit: true
#      minimum-idle: 10
#      maximum-pool-size: 100
#      validation-timeout: 5000 #连接被测试活动的最长时间 - 默认值：5秒
#    type: com.zaxxer.hikari.HikariDataSource
    generate-unique-name: true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 600000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      filter:
        slf4j:
          enabled: true
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 5000
          log-slow-sql: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.test.sql.entity